### ISSUE TITLE
Add tileset materials sample

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse-samples#6]
Add a sample demonstrating how to use tileset materials. The example in https://github.com/CesiumGS/cesium-omniverse/pull/406#issuecomment-1771561788 might be a good place to start.

CC @r-veenstra

**Comment by r-veenstra** [comment]
An elevation gradient mixed with imagery layers is probably a useful example to be included.  It covers some of the key nodes and also has a practical geospatial use.

![image](https://github.com/CesiumGS/cesium-omniverse-samples/assets/123468416/e3210a8d-b886-4b4e-9f7d-87aa79c091c7)

**Comment by lilleyse** [comment]
@r-veenstra that looks great!
